<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_ped 3 hodinami_video-stream html5-main-video</name>
   <tag></tag>
   <elementGuidId>4467410b-dbf9-4c99-98ab-031a25c88afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.video-stream.html5-main-video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>81b60559-7758-4049-bf25-3d51c0b41be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>faf2036d-003f-4cb9-91df-9db90727aa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-stream html5-main-video</value>
      <webElementGuid>e7720612-e7f8-4890-a041-6c7f1287e5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>7143ecc2-26b0-4bbf-aee0-1b8e3c44fa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.youtube.com/9b1f2cb5-9cbf-4ab6-984b-f7a25e1c7cf2</value>
      <webElementGuid>181190ca-d935-42f2-936b-ea4c89bd3ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;html5-video-container&quot;]/video[@class=&quot;video-stream html5-main-video&quot;]</value>
      <webElementGuid>df6abe11-9869-47d3-886f-baeeed34c0f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div/video</value>
      <webElementGuid>2807458c-d127-474c-b7ad-143008382781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>28395963-ceec-4107-ba2e-1171c326bb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://www.youtube.com/9b1f2cb5-9cbf-4ab6-984b-f7a25e1c7cf2']</value>
      <webElementGuid>73fc2244-7f53-41dd-87c6-7f5791b2cc81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
